# Generated by Django 3.0.5 on 2020-04-25 10:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20200414_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('BANK', 'BANK'), ('GROCERY', 'GROCERY'), ('PHARMACY', 'PHARMACY'), ('TRUCK', 'TRUCK')], default='UNKNOWN', max_length=20),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.TextField(default=None, max_length=100, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
        ),
        migrations.AddField(
            model_name='userslot',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Event'),
        ),
    ]
