# Generated by Django 3.0.5 on 2020-04-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('business', '0004_auto_20200414_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslot',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('READY_FOR_PICKUP', 'READY_FOR_PICKUP'), ('READY_FOR_DELIVERY', 'READY_FOR_DELIVERY')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='userslot',
            name='type',
            field=models.CharField(choices=[('READY-PICKUP', 'READY PICKUP'), ('DELIVERY', 'DELIVERY'), ('SELF', 'SELF')], default='SELF', max_length=20),
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.Item')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.UserSlot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
