# Generated by Django 3.0.5 on 2020-04-12 15:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('users_allowed', models.IntegerField(default=10)),
                ('slot_size_min', models.IntegerField(default=15)),
                ('business_type', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('BANK', 'BANK'), ('GROCERY', 'GROCERY'), ('PHARMACY', 'PHARMACY')], default='UNKNOWN', max_length=20)),
                ('start_time', models.TimeField(default='9:00')),
                ('end_time', models.TimeField(default='17:00')),
                ('address', models.TextField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=100)),
                ('customer_name', models.CharField(default=None, max_length=100)),
                ('mobile', models.CharField(blank=True, default='9766818825', max_length=10, null=True)),
                ('date', models.DateField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
        ),
    ]
