# Generated by Django 3.0.5 on 2020-04-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200414_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userslot',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='userslot',
            name='mobile',
        ),
    ]
