# Generated by Django 3.0.5 on 2020-04-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='slot_size_min',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='business',
            name='users_allowed',
            field=models.IntegerField(default=10),
        ),
    ]
