# Generated by Django 3.0.5 on 2020-04-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200404_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('BANKE', 'BANKE'), ('GROCERY', 'GROCERY'), ('PHARMACY', 'PHARMACY')], default='UNKNOWN', max_length=20),
        ),
    ]
