# Generated by Django 3.0.5 on 2020-04-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20200404_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='business',
            name='start_time',
            field=models.TimeField(default='9:00'),
        ),
    ]
