# Generated by Django 3.0.5 on 2020-04-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20200404_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslot',
            name='mobile',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
