# Generated by Django 3.0.5 on 2020-04-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_userslot_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslot',
            name='mobile',
            field=models.CharField(default='9766818825', max_length=10),
        ),
    ]
