# Generated by Django 3.0.5 on 2020-04-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20200404_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('BANK', 'BANK'), ('GROCERY', 'GROCERY'), ('PHARMACY', 'PHARMACY')], default='UNKNOWN', max_length=20),
        ),
    ]
