# Generated by Django 3.0.5 on 2020-04-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
                ('url', models.ImageField(null=True, upload_to='items')),
                ('size', models.IntegerField()),
                ('unit', models.CharField(choices=[('liters', 'liters'), ('ml', 'ml'), ('dozen', 'dozen'), ('kg', 'kg'), ('g', 'g')], max_length=10, null=True)),
                ('price', models.FloatField()),
            ],
        ),
    ]
