# Generated by Django 3.0.5 on 2020-04-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('VERIFICATION', 'Verification otp'), ('PAYMENT', 'Payment otp')], default='LOGIN', max_length=20),
        ),
    ]
