# Generated by Django 3.0.5 on 2020-04-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200413_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('Consumer', 'Consumer'), ('BusinessOwner', 'BusinessOwner')], default='Consumer', max_length=20),
            preserve_default=False,
        ),
    ]
